@startuml

    actor user
    participant "cbc: CBController" as cbc
    participant "cbs: CBService" as cbs
        participant "cbr: CBRepository" as cbr
    participant "cbv: CBValidator" as cbv


    user -> cbc: CBRequest

    title Caching a codeBlock
    header
    Explains how  a codeblock is cached
    endheader

    cbc->cbs: create(CBRequest)
    cbs->cbv: validate(CBRequest)
    cbs<-cbv: validate(CBRequest)
    cbs->cbs:
            note over cbs
                Incase of an error, return to controller.
            end note
    cbs->cbs: Build CBRequest
    cbs->cbr: create(CBRequest)
    cbr->cbs: void
    cbs->cbs: CBResponseBuilder.build(CodeBlock)
    cbc<-cbs: CBResponse
    user<-cbc: CBResponse



    @enduml